import 'package:firebase_core/firebase_core.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'dart:math';
import 'package:flutter/material.dart';

class RandomList {
  var dataList = [
    [
      1,
      "Family",
      "Kingdomino",
      4,
      25,
      "https://www.gamesweb.dk/spilleregler/kingdomino_eng.pdf",
      "https://sv1.picz.in.th/images/2022/03/02/rjleWe.png"
    ],
    [
      2,
      "Party",
      "Cockroach Poker Royal",
      6,
      25,
      "https://s3.amazonaws.com/geekdo-files.com/bgg214869?response-content-disposition=inline%3B%20filename%3D%22KakerlakenpokerRoyal_English_Rules.pdf%22&response-content-type=application%2Fpdf&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAJYFNCT7FKCE4O6TA%2F20220302%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20220302T141313Z&X-Amz-SignedHeaders=host&X-Amz-Expires=120&X-Amz-Signature=796321274b6bdeccb34075b0569021eff25614efb920604e3de0ac789c55683a",
      "https://cf.geekdo-images.com/loNpxkO1sWM_Xs4Pk2AMgA__opengraph/img/Y6BRtEbT11I4gCMx6z6FH5xFhBQ=/fit-in/1200x630/filters:strip_icc()/pic4129570.jpg"
    ],
    [
      3,
      "Party",
      "Dixit",
      6,
      30,
      "https://www.dropbox.com/s/3alu2vemij1tu6r/Dixit_TH_rule.pdf?dl=0&fbclid=IwAR2FrBN9srTdg0hTyZvJv-5gCqmJuJQrlXAyOlCQg6vLkVEv9BPL86qtD9E",
      "https://imgz.io/images/2022/03/02/kindpng_4768854.png"
    ],
    [
      4,
      "Party",
      "One Night Ultimate Werewolf ",
      10,
      10,
      "https://www.fgbradleys.com/rules/rules2/OneNightUltimateWerewolf-rules.pdf",
      "https://www.pngkit.com/png/full/150-1503873_one-night-ultimate-werewolf.png"
    ],
    [
      5,
      "Family",
      "Survive: Escape from Atlantis!",
      4,
      60,
      "https://www.fgbradleys.com/rules/rules4/Survive%20Escape%20from%20Atlantis%20-%20rules.pdf",
      "https://imgz.io/images/2022/03/02/1646227280164953.png"
    ],
    [
      6,
      "Family",
      "Camel Up",
      8,
      30,
      "https://www.fgbradleys.com/rules/rules2/CamelUp-rules.pdf",
      "https://imgz.io/images/2022/03/02/1646227995486533.png"
    ],
    [
      7,
      "Party",
      "Bang: Dice Game",
      8,
      15,
      "https://cdn.1j1ju.com/medias/ec/12/0a-bang-the-dice-game-rulebook.pdf",
      "http://2.bp.blogspot.com/-e_9atO9xDN4/VHyP1RHgqsI/AAAAAAAAAH4/FP8pQLremhU/s1600/pic1766481_md.jpg"
    ],
    [
      8,
      "Party",
      "Codenames",
      8,
      15,
      "https://www.fgbradleys.com/rules/rules4/codenames%20-%20rules.pdf",
      "https://guin.library.oregonstate.edu/sites/default/files/codenames.png"
    ],
    [
      9,
      "Family",
      "For Sale",
      6,
      30,
      "https://s3.amazonaws.com/geekdo-files.com/bgg184576?response-content-disposition=inline%3B%20filename%3D%22FOR_SALE_RULES2017_LOWRES.pdf%22&response-content-type=application%2Fpdf&X-Amz-Content-Sha256=UNSIGNED-PAYLOAD&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAJYFNCT7FKCE4O6TA%2F20220302%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20220302T141923Z&X-Amz-SignedHeaders=host&X-Amz-Expires=120&X-Amz-Signature=69c0f8996fa2e8311387f9e032d6a34b3832fe63ea9bd806fc9b121d01caeb96",
      "https://cf.geekdo-images.com/dJh9HkZC346NgPTAicJq_A__opengraph/img/sEGa2UCBuMOS0YWgOzlR2lHCAtY=/fit-in/1200x630/filters:strip_icc()/pic1513085.jpg"
    ],
    [
      10,
      "Family",
      "Ticket to Ride",
      5,
      60,
      "https://ncdn0.daysofwonder.com/tickettoride/de/img/tt_rules_2015_en.pdf",
      "https://cf.geekdo-images.com/ZWJg0dCdrWHxVnc0eFXK8w__imagepage/img/FcSGmLeIStNfb0l_qKSuOyz-rHY=/fit-in/900x600/filters:no_upscale():strip_icc()/pic38668.jpg"
    ],
    [
      11,
      "Family",
      "Potion Explosion",
      4,
      45,
      "https://cdn.1j1ju.com/medias/07/65/3f-potion-explosion-rulebook.pdf",
      "https://cf.geekdo-images.com/iAycB5JlPVO1Yf5zRMQitg__imagepage/img/ZbCACHDEPZkUuguRPsNdu7loH7k=/fit-in/900x600/filters:no_upscale():strip_icc()/pic2630294.png"
    ],
    [
      12,
      "Strategy",
      "Chinatown",
      5,
      60,
      "https://www.fgbradleys.com/rules/rules4/Chinatown%20-%20rules.pdf",
      "https://cf.geekdo-images.com/QnIOe-1wb8_zuxglKjAwOQ__imagepage/img/iwolJvl7y4glLadRIZn2a5oL5OY=/fit-in/900x600/filters:no_upscale():strip_icc()/pic2037509.png"
    ],
    [
      13,
      "Children's",
      "Rhino Hero",
      5,
      15,
      "https://cdn.haba.de/content/medias/manual/4789-rhino-hero-instructions-6s.pdf",
      "https://cf.geekdo-images.com/R_VAhiLCzl5RXKwSluvEbg__imagepage/img/-dTjedA8XBaxPdAW6keoboUE5YU=/fit-in/900x600/filters:no_upscale():strip_icc()/pic3271388.jpg"
    ],
    [
      14,
      "Family",
      "UNO",
      10,
      30,
      "https://service.mattel.com/instruction_sheets/42001pr.pdf",
      "https://cf.geekdo-images.com/SU-OL7XWn7BOiSYevyTThw__imagepage/img/uotP5LoO-WmXqCbqFSpYP01npp0=/fit-in/900x600/filters:no_upscale():strip_icc()/pic981505.jpg"
    ],
    [
      15,
      "Party",
      "Exploding Kittens",
      5,
      15,
      "https://www.fgbradleys.com/rules/rules2/ExplodingKittens-rules.pdf",
      "https://cf.geekdo-images.com/N8bL53-pRU7zaXDTrEaYrw__imagepage/img/qdivOjtkEd8Jma35bdI3mOwaoZg=/fit-in/900x600/filters:no_upscale():strip_icc()/pic2691976.png"
    ],
    [
      16,
      "Family",
      "Marrakech",
      4,
      30,
      "https://www.ultraboardgames.com/marrakech/game-rules.php",
      "https://cf.geekdo-images.com/HQ7axXisPwqwkDsfI6FeoQ__imagepage/img/VozfUKCBT_iYoOJzuu4yfPlb2UA=/fit-in/900x600/filters:no_upscale():strip_icc()/pic6531656.jpg"
    ],
    [
      17,
      "Party",
      "The Resistance: Avalon",
      10,
      30,
      "https://www.fgbradleys.com/rules/rules4/Resistance%20Avalon%20-%20rules.pdf",
      "https://cf.geekdo-images.com/LPa6rsGcv8S0-OeNjCOAEQ__imagepage/img/3xVP5JSdSfFbo2c1nnZS5xxGhfI=/fit-in/900x600/filters:no_upscale():strip_icc()/pic1398895.jpg"
    ],
    [
      18,
      "Children's",
      "Geistes Blitz Spooky Doo",
      8,
      20,
      "https://world-of-board-games.com.sg/docs/Geistesblitz-Spooky-Doo.pdf",
      "https://dt.lnwfile.com/uhj3um.jpg"
    ],
    [
      19,
      "Party",
      "Coup",
      6,
      15,
      "https://www.qugs.org/rules/r131357.pdf",
      "https://cf.geekdo-images.com/MWhSY_GOe2-bmlQ2rntSVg__imagepage/img/HPKaW4sG3jlaO3MM5V6x0Ks0DGI=/fit-in/900x600/filters:no_upscale():strip_icc()/pic2016054.jpg"
    ],
    [
      20,
      "Children's",
      "Spinderella",
      4,
      20,
      "https://cdn.1j1ju.com/medias/4b/eb/1c-spinderella-rulebook.pdf",
      "https://cf.geekdo-images.com/83b12oXwbrUmQQg0CrPuzg__imagepage/img/X2TUh7O18s5nB6b52gdgrWD4cu8=/fit-in/900x600/filters:no_upscale():strip_icc()/pic2385041.jpg"
    ],
    [
      21,
      "Family",
      "King of Tokyo",
      6,
      30,
      "https://www.fgbradleys.com/rules/rules6/King%20of%20Tokyo%20-%20rules.pdf",
      "https://cf.geekdo-images.com/m_RzXpHURC0_xLkvRSR_sw__imagepage/img/oSNvtltDuWj3LP74IEFj8Ov2B0k=/fit-in/900x600/filters:no_upscale():strip_icc()/pic3043734.jpg"
    ],
    [
      22,
      "Strategy",
      "Catan",
      4,
      120,
      "https://www.fgbradleys.com/rules//SettlersOfCatan.pdf",
      "https://cf.geekdo-images.com/W3Bsga_uLP9kO91gZ7H8yw__imagepage/img/M_3Vg1j2HlNgkv7PL2xl2BJE2bw=/fit-in/900x600/filters:no_upscale():strip_icc()/pic2419375.jpg"
    ],
    [
      23,
      "Party",
      "Sheriff of Nottingham",
      5,
      60,
      "https://cdn.1j1ju.com/medias/d3/7f/61-sheriff-of-nottingham-rulebook.pdf",
      "https://cf.geekdo-images.com/BBgLFKUzr6tcKtlIM2JSFw__imagepage/img/_3bSh9NeLxkL23XBruNlzxk5QCM=/fit-in/900x600/filters:no_upscale():strip_icc()/pic2075830.jpg"
    ],
    [
      24,
      "Family",
      "Splendor",
      4,
      30,
      "https://www.fgbradleys.com/rules/rules4/Splendor%20-%20rules.pdf",
      "https://cf.geekdo-images.com/rwOMxx4q5yuElIvo-1-OFw__imagepage/img/qXhBOrqJMEeA0pe6TMzWNZUTlbk=/fit-in/900x600/filters:no_upscale():strip_icc()/pic1904079.jpg"
    ],
    [
      25,
      "Strategy",
      "Small World",
      5,
      80,
      "https://ncdn1.daysofwonder.com/smallworld/en/img/sw_rules_2015_en.pdf",
      "https://cf.geekdo-images.com/aoPM07XzoceB-RydLh08zA__imagepage/img/lHmv0ddOrUvpiLcPeQbZdT5yCEA=/fit-in/900x600/filters:no_upscale():strip_icc()/pic428828.jpg"
    ],
    [
      26,
      "Party",
      "Saboteur",
      10,
      30,
      "https://cdn.1j1ju.com/medias/83/8a/e7-saboteur-rulebook.pdf",
      "https://cf.geekdo-images.com/0vJwP6NGa7GHPZKC3gplUw__imagepage/img/HTsjdbMkBnY50FfT6GOECkceD0Y=/fit-in/900x600/filters:no_upscale():strip_icc()/pic3989824.jpg"
    ],
    [
      27,
      "Family",
      "Century Spice Road",
      5,
      45,
      "https://www.fgbradleys.com/rules/rules5/Century-Spice_Road_EN_Rules.pdf",
      "https://cf.geekdo-images.com/0_KEDk4lCvryf1Ju3YQJxA__imagepage/img/4pU8XNwimU2Dlx097R2Fd7PQxxI=/fit-in/900x600/filters:no_upscale():strip_icc()/pic3339551.jpg"
    ],
    [
      28,
      "Strategy ",
      "Pandemic",
      4,
      45,
      "https://www.fgbradleys.com/rules/rules2/Pandemic-rules.pdf",
      "https://cf.geekdo-images.com/S3ybV1LAp-8SnHIXLLjVqA__imagepage/img/kIBu-2Ljb_ml5n-S8uIbE6ehGFc=/fit-in/900x600/filters:no_upscale():strip_icc()/pic1534148.jpg"
    ],
    [
      29,
      "Family",
      "Love Letter",
      4,
      20,
      "https://www.fgbradleys.com/rules/rules2/LoveLetter-rules.pdf",
      "https://cf.geekdo-images.com/T1ltXwapFUtghS9A7_tf4g__imagepage/img/wf3HgW2e24O0mcsB5OIHJnxaeIM=/fit-in/900x600/filters:no_upscale():strip_icc()/pic1401448.jpg"
    ],
    [
      30,
      "Abstract",
      "Patchwork",
      2,
      30,
      "https://www.fgbradleys.com/rules/rules4/Patchwork%20-%20rules.pdf",
      "https://cf.geekdo-images.com/wLW7pFn0--20lEizEz5p3A__imagepage/img/qDuX2TRjK3utCghPRUfrG42fcFk=/fit-in/900x600/filters:no_upscale():strip_icc()/pic2270442.jpg"
    ],
    [
      31,
      "Abstract",
      "Blokus",
      4,
      20,
      "https://service.mattel.com/instruction_sheets/BJV44-Eng.pdf",
      "https://cf.geekdo-images.com/96YA5wUJDxtPkmPxemr5Qg__imagepage/img/prHITmtjGOroRq5ow1E8-h5Yy-o=/fit-in/900x600/filters:no_upscale():strip_icc()/pic2197702.jpg"
    ],
    [
      32,
      "Family",
      "Las Vegas",
      5,
      30,
      "https://tesera.ru/images/items/332433/Vegas.pdf",
      "https://cf.geekdo-images.com/aQJ0HRKx2mobP0g3FCeR_Q__imagepage/img/dGDbGZ6oJldnwjooOcHku0kBWg0=/fit-in/900x600/filters:no_upscale():strip_icc()/pic1261796.jpg"
    ],
    [
      33,
      "Party",
      "Secret hitler",
      10,
      45,
      "https://www.secrethitler.com/assets/Secret_Hitler_Rules.pdf",
      "https://cf.geekdo-images.com/rAQ3hIXoH6xDcj41v9iqCg__imagepage/img/QTDaAfkaWhobmpHVlfVtBz30OH0=/fit-in/900x600/filters:no_upscale():strip_icc()/pic5164305.jpg"
    ],
    [
      34,
      "Party",
      "Ultimate Werewolf: Deluxe Edition",
      75,
      30,
      "https://board-games-galore.fandom.com/wiki/Ultimate_Werewolf",
      "https://cf.geekdo-images.com/dncdxD1g4dxMh9e8oKlzbg__imagepage/img/OJCobAFPlUjpofaB8QStLAQnqcE=/fit-in/900x600/filters:no_upscale():strip_icc()/pic1878492.png"
    ],
    [
      35,
      "Party",
      "Concept",
      12,
      40,
      "https://www.fgbradleys.com/rules/rules2/Concept-rules.pdf",
      "https://cf.geekdo-images.com/hHFs0_KRoW_FJ0cMIVgZcw__imagepage/img/ALoCsrBCh-VtpEt-LaZq3MrWPL0=/fit-in/900x600/filters:no_upscale():strip_icc()/pic4991925.jpg"
    ],
    [
      36,
      "Thematic",
      "Mysterium",
      7,
      42,
      "https://www.fgbradleys.com/rules/rules3/MysteriumRules.pdf",
      "https://cf.geekdo-images.com/wfeAiLK5n5hD1omhnlYLLA__imagepage/img/FAbfi09ZD0NHVa9psSeSrBZPgms=/fit-in/900x600/filters:no_upscale():strip_icc()/pic2601683.jpg"
    ],
    [
      37,
      "Strategy",
      "Samurai",
      4,
      60,
      "https://www.fgbradleys.com/rules/rules2/Samurai-rules.pdf",
      "https://cf.geekdo-images.com/o9-sNXmFS_TLAb7ZlZ4dRA__imagepage/img/yXniplPYXixomNLic5j_DsgF9xI=/fit-in/900x600/filters:no_upscale():strip_icc()/pic3211873.jpg"
    ],
    [
      38,
      "Strategy",
      "Power Grid",
      6,
      120,
      "https://www.fgbradleys.com/rules/rules2/PowerGrid-rules.pdf",
      "https://cf.geekdo-images.com/yd6LuatytHRhcFCxCf-EEg__imagepage/img/-tc_XLn5RXXaNfQHtlpf4BhyWPM=/fit-in/900x600/filters:no_upscale():strip_icc()/pic4459753.jpg"
    ],
    [
      39,
      "Party",
      "Cash 'n Guns (Second Edition) ",
      8,
      30,
      "https://www.fgbradleys.com/rules/rules2/CashnGuns-rules.pdf",
      "https://cf.geekdo-images.com/b4qSA5fvVJe9QQOKPCMoNA__imagepage/img/heCeM3C6Eu3n9iC59UG6LOSqagk=/fit-in/900x600/filters:no_upscale():strip_icc()/pic2907864.jpg"
    ],
    [
      40,
      "Party",
      "Mascarade",
      13,
      30,
      "https://www.fgbradleys.com/rules/rules2/Mascarade-rules.pdf",
      "https://cf.geekdo-images.com/OS3ckk3rZbwFi8en1rjiGQ__imagepage/img/RO_a7dT8-yeaCDAmIZ2XipmUgHk=/fit-in/900x600/filters:no_upscale():strip_icc()/pic1762410.jpg"
    ],
    [
      41,
      "Strategy",
      "Evolution",
      6,
      60,
      "https://www.fgbradleys.com/rules/rules3/EvolutionRules.pdf",
      "https://cf.geekdo-images.com/wo_EYno7S66psGPMl_JtiQ__imagepage/img/zkFtiwu5gSoDo3rUWLrfdlVzpjE=/fit-in/900x600/filters:no_upscale():strip_icc()/pic3543505.jpg"
    ],
    [
      42,
      "Strategy",
      "Istanbul",
      5,
      60,
      "https://www.fgbradleys.com/rules/rules4/Istanbul%20-%20rules.pdf",
      "https://cf.geekdo-images.com/PHH9Mreen2sBcxV6ZsE3ew__imagepage/img/0HkubGOJ4N2zOpBAFyK-LiF0Ad8=/fit-in/900x600/filters:no_upscale():strip_icc()/pic1885326.jpg"
    ],
    [
      43,
      "Party",
      "Spyfall",
      8,
      15,
      "https://www.fgbradleys.com/rules/rules6/Spyfall%20-%20rules.pdf",
      "https://cf.geekdo-images.com/Ehx72XRdSeQHISVXcZVnHg__imagepage/img/7wwISG7kfg1a-dIi07n6n9fAK2Y=/fit-in/900x600/filters:no_upscale():strip_icc()/pic2453926.jpg"
    ],
    [
      44,
      "Party",
      "Telestrations",
      8,
      30,
      "https://www.fgbradleys.com/rules/rules4/Telestrations%20-%20rules.pdf",
      "https://cf.geekdo-images.com/oc3u6OQpJkf9TvDw4iI9xA__imagepage/img/pqfDnwFGf2MqIP307y0La81AIRg=/fit-in/900x600/filters:no_upscale():strip_icc()/pic4991936.jpg"
    ],
    [
      45,
      "Strategy",
      "Taluva",
      4,
      45,
      "https://www.fgbradleys.com/rules/rules4/Taluva%20-%20rules.pdf",
      "https://cf.geekdo-images.com/PC01tlKF5hf3et7F3mtHtw__imagepage/img/eRCnBGyrfcbSk8hlOoe69e3ykPM=/fit-in/900x600/filters:no_upscale():strip_icc()/pic1948254.png"
    ],
    [
      46,
      "Party",
      "Dead Last",
      12,
      90,
      "https://tesera.ru/images/items/794133/Dead%20Last%20Rulebook.pdf",
      "https://cf.geekdo-images.com/o-Z0bj1YVYgsnaVVR5yXOQ__imagepage/img/FSbZY58wHm0LzvwBIu6a4C3V7xU=/fit-in/900x600/filters:no_upscale():strip_icc()/pic3021686.jpg"
    ],
    [
      47,
      "Abstract",
      "Azul",
      4,
      45,
      "https://www.fgbradleys.com/rules/rules5/Azul%20-%20rules.pdf",
      "https://cf.geekdo-images.com/tz19PfklMdAdjxV9WArraA__imagepage/img/K2rwaCiB7-p41iVG3_BCdUDBo8o=/fit-in/900x600/filters:no_upscale():strip_icc()/pic3718275.jpg"
    ],
    [
      48,
      "Family",
      "Celestia",
      6,
      30,
      "https://cdn.1j1ju.com/medias/ba/60/48-celestia-rulebook.pdf",
      "https://cf.geekdo-images.com/VddNmZyVWsxyebeGbu4-dg__imagepage/img/FCi3FN0ZUcCjVr5p2taav89oyF0=/fit-in/900x600/filters:no_upscale():strip_icc()/pic2577990.jpg"
    ],
    [
      49,
      "Family",
      "I'm the Boss!",
      6,
      60,
      "https://world-of-board-games.com.sg/docs/Im-the-Boss.pdf",
      "https://cf.geekdo-images.com/apSWtxrC9oG-rBSg0Gheag__imagepage/img/0HkFAqe5QEOsfAW_VJk0I0G5ah0=/fit-in/900x600/filters:no_upscale():strip_icc()/pic130807.jpg"
    ],
    [
      50,
      "Family",
      "Sagrada",
      4,
      45,
      "https://www.fgbradleys.com/rules/rules6/Sagrada%20-%20rules.pdf",
      "https://cf.geekdo-images.com/PZt3EAAGV3dFIVuwMR0AEw__imagepage/img/F8DS3hdZfVIcxVpPSZV7DMLrPJ4=/fit-in/900x600/filters:no_upscale():strip_icc()/pic3525224.jpg"
    ],
    [
      51,
      "Family",
      "Carcassonne",
      5,
      45,
      "https://www.fgbradleys.com/rules/rules2/Carcassonne-rules.pdf",
      "https://cf.geekdo-images.com/okM0dq_bEXnbyQTOvHfwRA__imagepage/img/axGbn7f0x6UUb07DmzX9hg5TwIo=/fit-in/900x600/filters:no_upscale():strip_icc()/pic6544250.png"
    ],
    [
      52,
      "Party",
      "Salem 1692",
      12,
      35,
      "http://boardgamecircus.com/wp-content/uploads/2018/10/Salem-1692-Rulebook-EN.pdf",
      "https://cf.geekdo-images.com/xUurReSy2Amlx4hGj1fPvQ__imagepage/img/JeVnUUuC07NrrLtz-XG8tW2VxKU=/fit-in/900x600/filters:no_upscale():strip_icc()/pic4204062.jpg"
    ],
    [
      53,
      "Strategy ",
      "7 Wonders",
      7,
      30,
      "https://www.fgbradleys.com/rules/rules2/7Wonders-rules.pdf",
      "https://cf.geekdo-images.com/RvFVTEpnbb4NM7k0IF8V7A__imagepage/img/zruHYxY2_jx-796WgsDj7hitidQ=/fit-in/900x600/filters:no_upscale():strip_icc()/pic860217.jpg"
    ],
    [
      54,
      "Strategy",
      "Terraforming Mars",
      5,
      120,
      "https://www.fgbradleys.com/rules/rules4/Terraforming%20Mars%20-%20rules.pdf",
      "https://cf.geekdo-images.com/wg9oOLcsKvDesSUdZQ4rxw__imagepage/img/FS1RE8Ue6nk1pNbPI3l-OSapQGc=/fit-in/900x600/filters:no_upscale():strip_icc()/pic3536616.jpg"
    ],
    [
      55,
      "Family",
      "Queendomino",
      4,
      25,
      "https://www.fgbradleys.com/rules/rules6/Queendomino%20-%20rules.pdf",
      "https://cf.geekdo-images.com/_6VtTmeI4e7cORxFWRC7Og__imagepage/img/0Jd5ZTmedIvntg9wBIJJiuwUz7w=/fit-in/900x600/filters:no_upscale():strip_icc()/pic3672901.png"
    ],
    [
      56,
      "Thematic",
      "Room 25",
      6,
      30,
      "https://cdn.1j1ju.com/medias/3a/85/e2-room-25-ultimate-rulebook.pdf",
      "https://cf.geekdo-images.com/urP8ZiJeGJ_WFJ5ovqA5kg__imagepage/img/-mYp-xBWez4cHhHbWcvZbOXqliI=/fit-in/900x600/filters:no_upscale():strip_icc()/pic3046708.jpg"
    ],
    [
      57,
      "Family",
      "Gizmos",
      4,
      50,
      "https://cmon-files.s3.amazonaws.com/pdf/assets_item/resource/126/Rulebook_Gizmos.pdf",
      "https://cf.geekdo-images.com/zin82Hg4MXck86t8fzbsdA__imagepage/img/NDB1PCAmapf28Im6HC63UbgwIsU=/fit-in/900x600/filters:no_upscale():strip_icc()/pic4169718.png"
    ],
    [
      58,
      "Strategy",
      "Brass: Birmingham",
      4,
      120,
      "http://files.roxley.com/Brass-Birmingham-Rulebook-2018.11.20-highlights.pdf",
      "https://cf.geekdo-images.com/x3zxjr-Vw5iU4yDPg70Jgw__imagepage/img/-17KkOmxbTu2slJTabGrkO8ZW8s=/fit-in/900x600/filters:no_upscale():strip_icc()/pic3490053.jpg"
    ]
  ];
  final _random = new Random();
  getListData() {
    int random = Random() as int;
    var element = dataList[_random.nextInt(dataList.length)];
  }
  
}
